// The committed helper must equal the one its source produces.
//
// pkg/dsh-plugin-market/market-core.mjs is generated by tools/build-helper.mjs. It is
// committed so the plugin can be installed straight from a clone, which means it can
// go stale. This recomputes it WITHOUT writing and compares.
//
// Usage: node tools/check-sync.mjs
import { readFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildHelper, helperProblems, readHelperSource } from './helper-build.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')

let bad = 0
const check = (label, ok, detail) => { if (!ok) bad += 1; console.log((ok ? '  OK    ' : '  FAIL  ') + label + (detail ? '  -> ' + detail : '')) }

const expected = buildHelper(readHelperSource(here))
const problems = helperProblems(expected)
check('the source builds a complete helper', problems.length === 0, problems.join('; '))

const pkgCopy = join(root, 'pkg', 'dsh-plugin-market', 'market-core.mjs')
check('the committed helper exists', existsSync(pkgCopy))
if (existsSync(pkgCopy)) {
  const actual = readFileSync(pkgCopy, 'utf8')
  if (actual === expected) {
    check('the committed helper matches its source', true, Buffer.byteLength(actual) + ' bytes')
  } else {
    check('the committed helper matches its source', false,
      actual.length + ' vs ' + expected.length + ' bytes — run: node tools/build-helper.mjs')
  }
}

// The package must also be self-consistent: index.js runs a script by this name.
const indexSrc = readFileSync(join(root, 'pkg', 'dsh-plugin-market', 'index.js'), 'utf8')
check('the host looks for the same script name', indexSrc.includes("SCRIPT_NAME = 'market-core.mjs'"))
const pkgJson = JSON.parse(readFileSync(join(root, 'pkg', 'dsh-plugin-market', 'package.json'), 'utf8'))
check('the package ships the helper', (pkgJson.files || []).includes('market-core.mjs'))

console.log('\n' + (bad === 0 ? 'ARTIFACT SYNC OK' : 'ARTIFACT SYNC FAILED (' + bad + ')'))
process.exit(bad === 0 ? 0 : 1)
